[dependencies]
proc-macro2 = { version = "1.0", features = [] }
quote = "1.0"
module_path_extractor = "0.1"
serde = { workspace = true, optional = true }
moddef = { version = "0.2.6" }
syn = { version = "2.0", features = ["full", "visit-mut", "visit"] }

[dev-dependencies]
trybuild = "*"

[features]
default = []
serde = ["dep:serde"]

[lib]
proc-macro = true

[package]
authors = ["Eran Boodnero <eran@eran.codes>"]
categories = ["rust-patterns"]
description = "Compile-time state machine magic for Rust: Zero-boilerplate typestate patterns with automatic transition validation"
documentation = "https://docs.rs/statum"
edition = "2021"
keywords = ["enum", "typestate", "fsm", "finite-state", "state-machine"]
license = "MIT"
name = "statum-macros"
readme = "README.md"
repository = "https://github.com/eboody/statum"
version = "0.2.0"
