[dependencies]
proc-macro2 = { version = "1.0", features = [] }
quote = "1.0"
module_path_extractor = "0.2.1"
moddef = { version = "0.2.6" }
syn = { version = "2.0", features = ["full", "visit-mut", "visit"] }

[dev-dependencies]
bon = "3.3.2"
futures = "0.3"
statum-core = { path = "../statum-core", version = "0.3.4" }
trybuild = "1.0"

[features]
default = []

[lib]
proc-macro = true

[package]
authors = ["Eran Boodnero <eran@eran.codes>"]
categories = ["rust-patterns"]
description = "Compile-time state machine magic for Rust: Zero-boilerplate typestate patterns with automatic transition validation"
documentation = "https://docs.rs/statum"
edition = "2024"
keywords = ["enum", "typestate", "fsm", "finite-state", "state-machine"]
license = "MIT"
name = "statum-macros"
readme = "README.md"
repository = "https://github.com/eboody/statum"
version = "0.3.4"
