[package]
authors = ["Eran Boodnero <eran@eran.codes>"]
categories = ["rust-patterns"]
description = "Compile-time state machine magic for Rust: Zero-boilerplate typestate patterns with automatic transition validation"
documentation = "https://docs.rs/statum"
edition = "2021"
keywords = ["enum", "typestate", "fsm", "finite-state", "state-machine"]
license = "MIT"
name = "statum"
readme = "README.md"
repository = "https://github.com/eboody/statum"
version = "0.3.2"

[dependencies]
bon = { version = "3.3.2", features = [
  "experimental-getter",
  "experimental-overwritable",
  "implied-bounds",
] }
statum-core = { path = "../statum-core", version = "0.3.2" }
statum-macros = { path = "../statum-macros", version = "0.3.2" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
